### ISSUE TITLE
No module named 'torch'

### ISSUE THREAD

**Issue by cbpuschmann** [chainsawriot/grafzahl#20]
When running grafzahl() on macOS Monterey following the example code I get

Error in py_run_file_impl(path.expand(file), local, convert) : 
  ModuleNotFoundError: No module named 'torch'

Sounds a lot like:
https://github.com/rstudio/reticulate/issues/909

Any ideas?

**Comment by cbpuschmann** [comment]
(Get the same error on Ubuntu. Note that this is with the development rather than CRAN version.)

**Comment by kasperwelbers** [comment]
Same, but strangely this only occurs for me when I restart R. If I re-run setup_grafzahl (with force is TRUE) it works again. But then when I restart R it breaks again.

(on Ubuntu)

**Comment by chainsawriot** [comment]
Please check with this:

https://github.com/chainsawriot/grafzahl/wiki/setup_grafzahl

**Comment by cbpuschmann** [comment]
Thanks. The error unfortunately also occurs with setup_grafzahl(cuda = FALSE) and seems to be unrelated to cuda. While detect_conda() returns TRUE, just running detect_cuda() results in 
Error in py_run_file_impl(path.expand(file), local, convert) : 
  ModuleNotFoundError: No module named 'torch'
🤔

**Comment by chainsawriot** [comment]
How about

```bash
conda install -n grafzahl_condaenv pytorch -y
conda activate grafzahl_condaenv
python -c "import torch"
```

**Comment by cbpuschmann** [comment]
Finally figured it out, it was a rather dumb issue with multiple installations of miniconda getting all confused. Solved it by setting Sys.setenv(RETICULATE_MINICONDA_PATH = "/Users/cp/miniconda3") which was the correct path for my machine. Is that any different from GRAFZAHL_MINICONDA_PATH?

**Comment by cbpuschmann** [comment]
Note that for me at least a manual install of miniconda was necessary. Perhaps others can check whether this is a MacOS issue.

**Comment by chainsawriot** [comment]
@cbpuschmann The updated version 505019be5e14e37f16f3853df4f755d82b0800e9 provides better feedback for failed installation and does checks afterward.

I have also updated the Wiki for [non-CUDA manual installation](https://github.com/chainsawriot/grafzahl/wiki/setup_grafzahl#Noncuda).

`GRAFZAHL_MINICONDA_PATH` is more for testing and functionally it just masks the default `RETICULATE_MINICONDA_PATH` if it is not ""; maybe I should disable it in later versions.
