### ISSUE TITLE
Error in py_call_impl

### ISSUE THREAD

**Issue by tweedmann** [chainsawriot/grafzahl#22]
Hello there,

thanks for this amazing package. I tried it out yesterday and I was able to train a model. However, once I wanted to use the trained model to predict new data, I received the following error message:

_Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: 'use_cuda' set to True when cuda is unavailable. Make sure CUDA is available or set use_cuda=False._

The error message appears whether I set use_cude to TRUE or FALSE.

Do you have any idea why I receive this error message or what I could do? 

Thanks in advance
Tobias

**Comment by chainsawriot** [comment]
`sessionInfo()`, please.

**Comment by chainsawriot** [comment]
Also  #19

Please make sure you are using the github version.

**Comment by tweedmann** [comment]
Apologies, I have overlooked #19 before. After working with the github version, the error message disappeared. Thanks for your help!
